### ISSUE TITLE
Issue with starting

### ISSUE THREAD

**Issue by xxxNEXON** [achang28/PayPal-Clone#1]
internal/modules/cjs/loader.js:615
    throw err;
    ^

Error: Cannot find module 'open'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:613:15)
    at Function.Module._load (internal/modules/cjs/loader.js:539:25)
    at Module.require (internal/modules/cjs/loader.js:667:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/var/www/html/cas/server.js:7:14)
    at Module._compile (internal/modules/cjs/loader.js:738:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:749:10)
    at Module.load (internal/modules/cjs/loader.js:630:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:570:12)
    at Function.Module._load (internal/modules/cjs/loader.js:562:3)

That's the error, i tried
- npm version changing, updating, downgrading
- npm reinstall
- npm modules and lock.json reinstall

I does not know what to do :p

**Comment by BasToTheMax** [comment]
idk

**Comment by SB3020202** [comment]
This is what I get after I run "npm start"

> pay-pal-clone@0.0.1 start
> npm run serve:dev


> pay-pal-clone@0.0.1 serve:dev
> webpack-dev-server --open --env dev

CLI for webpack must be installed.
  webpack-cli (https://github.com/webpack/webpack-cli)

We will use "npm" to install the CLI via "npm install -D webpack-cli".
Do you want to install 'webpack-cli' (yes/no): yes
Installing 'webpack-cli' (running 'npm install -D webpack-cli')...
npm ERR! code ERESOLVE
npm ERR! ERESOLVE could not resolve
npm ERR!
npm ERR! While resolving: eslint-config-airbnb@19.0.4
npm ERR! Found: eslint-plugin-jsx-a11y@1.5.5
npm ERR! node_modules/eslint-plugin-jsx-a11y
npm ERR!   dev eslint-plugin-jsx-a11y@"^1.0.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint-plugin-jsx-a11y@"^6.5.1" from eslint-config-airbnb@19.0.4
npm ERR! node_modules/eslint-config-airbnb
npm ERR!   dev eslint-config-airbnb@"^19.0.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: eslint-plugin-jsx-a11y@6.7.1
npm ERR! node_modules/eslint-plugin-jsx-a11y
npm ERR!   peer eslint-plugin-jsx-a11y@"^6.5.1" from eslint-config-airbnb@19.0.4
npm ERR!   node_modules/eslint-config-airbnb
npm ERR!     dev eslint-config-airbnb@"^19.0.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\sidim\AppData\Local\npm-cache\_logs\2023-02-22T23_18_17_009Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\sidim\AppData\Local\npm-cache\_logs\2023-02-22T23_18_17_009Z-debug-0.log
undefined

What should I do to fix it?
